<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Kamrans-MacBook-Pro.local" name="com.qa.havenlife.tests.ValuesPageTest" tests="5" failures="0" timestamp="2020-08-17T17:23:16 EDT" time="10.971" errors="1">
  <testcase name="verifyValuesGreaterZero" time="0.000" classname="com.qa.havenlife.tests.ValuesPageTest">
    <skipped/>
  </testcase> <!-- verifyValuesGreaterZero -->
  <system-out/>
  <testcase name="verifyAllValuesFormattedAsCurrency" time="0.000" classname="com.qa.havenlife.tests.ValuesPageTest">
    <skipped/>
  </testcase> <!-- verifyAllValuesFormattedAsCurrency -->
  <system-out/>
  <testcase name="setUp" time="10.971" classname="com.qa.havenlife.tests.ValuesPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.havenlife.pages.ValuesPage.<init>(ValuesPage.java:15)
at com.qa.havenlife.tests.ValuesPageTest.setUp(ValuesPageTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase name="verifyCountOfValues" time="0.000" classname="com.qa.havenlife.tests.ValuesPageTest">
    <skipped/>
  </testcase> <!-- verifyCountOfValues -->
  <system-out/>
  <testcase name="verifyTotalBalance" time="0.000" classname="com.qa.havenlife.tests.ValuesPageTest">
    <skipped/>
  </testcase> <!-- verifyTotalBalance -->
  <system-out/>
</testsuite> <!-- com.qa.havenlife.tests.ValuesPageTest -->
